### ISSUE TITLE
Add “Validate token” button

### ISSUE THREAD

**Issue by marvinruder** [Densaugeo/uploadserver#26]
Currently, the token is validated after the file is completely uploaded. When a large file is uploaded using a slow internet connection, this can take a while. When I then forgot to add the token or added a misspelled token, I need to upload the entire file again. 

It would be helpful to have a button “Validate token” right next to the token input field that sends the token to the server, which then replies with either “200 Token is valid”, “200 No token necessary” or “403 Token is enabled on this server, and your token is wrong”. This way, I can quickly and easily check whether a file upload would be accepted by the server before I waste time uploading it with a wrong token. 

I am willing to propose a PR if this feature if you are generally open for such a feature.

**Comment by Densaugeo** [comment]
This is a good point, and I'm fairly sure it's also a DoS vulnerability - I would like to have the server *always* validate tokens and client keys first at some point.

Either way #24 is making a breaking change, so I want to get that merged first. This'll be one of the first things to revisit after that.

**Comment by Densaugeo** [comment]
#24 is merged now, go ahead and make a PR if you want to include this.

Looks like the current file upload payload sometimes has the token at the end, so validating all requests before accepting the upload is not really possible. I think I'll just say anyone worried about DoS will have to enable mTLS.

Rather than add a button, I think the token validation should be fully automated, otherwise a user forget to check their token before uploading a large file. Perhaps check it as part of the regular upload handler.

**Comment by marvinruder** [comment]
Made a proposal at #27

**Comment by Densaugeo** [comment]
Thanks for the PR! I've also published a new version now with the changes from this and #23 and #24.
