### ISSUE TITLE
Python's cgi is deprecated and will soon be removed

### ISSUE THREAD

**Issue by cheweytoo** [Densaugeo/uploadserver#37]
uploadserver uses ```cgi.FieldStorage()``` - unfortunately, the ```cgi``` module is about to be removed from the Python standard libs with the release of Python 3.13, which is the next upcoming release. See https://peps.python.org/pep-0594/#cgi

I have no immediate solution for this, but it will need to be considered in the not too distant future.

**Comment by Densaugeo** [comment]
I think there was a project somewhere to provide cgi as an installed module. If not, it's always possible to copy the bits we use out of the cgi module's source. The biggest complication I see is I'm not sure how specifying different dependencies for different Python versions works - never tried to do that before.

Anyway, with 3.12 releasing soon, I'll probably look into 3.13 support after that. I'll leave this issue open since I'll probably be working on it fairly soon.

**Comment by Densaugeo** [comment]
I've found a solution - I copied cgi.py out of Python's core libraries and saved it as a submodule in uploadserver. On 3.13+ it'll use that copy, and now I hope cgi.py doesn't get hit by too many breaking changes.

fa233ba
