### ISSUE TITLE
Error 404 - File not found

### ISSUE THREAD

**Issue by aurelien-m** [Densaugeo/uploadserver#43]
Hello! I cannot access the upload page, as I'm getting this error:

![Screenshot from 2024-03-27 10-59-41](https://github.com/Densaugeo/uploadserver/assets/29719028/a2c3bee1-60dd-4435-b7cb-4e2d16748ea4)

I tried using `python3 -m uploadserver` and `python3 -m uploadserver --basic-auth-upload hello:world`

**Comment by Densaugeo** [comment]
It looks like you visited `/archives/upload` instead of just `/upload`. Try doing the exact same thing but navigating to `http://172.16.3.150:8000/upload`.

For a while I've want to make the startup message print a clickable URL, but it turns out that servers can have multiple hostnames or IP addresses which makes that complicated.

**Comment by Densaugeo** [comment]
Closed due to inactivity.
